const weight = new Array<number>();

weight.push(3);
weight.push(7);
weight.push(7);
weight.push(7);
weight.push(1);
weight.push(7);
weight.push(7);
weight.push(1);
weight.push(3);
weight.push(8);
weight.push(7);
weight.push(8);
weight.push(7);
weight.push(6);
weight.push(7);
weight.push(7);
weight.push(8);
weight.push(6);
weight.push(8);
weight.push(8);
weight.push(8);
weight.push(5);
weight.push(6);
weight.push(8);
weight.push(8);
weight.push(7);
weight.push(3);
weight.push(1);
weight.push(8);
weight.push(7);
weight.push(2);
weight.push(4);

export default weight;
